"""DeepStream nvinfer configuration generation."""

import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Optional, Union

from ..config import get_config, Precision, SAM3DeepStreamConfig

logger = logging.getLogger(__name__)


@dataclass
class NvInferConfig:
    """nvinfer plugin configuration."""
    gpu_id: int = 0
    net_scale_factor: float = 0.00392156862745098  # 1/255
    model_engine_file: str = "sam3_encoder.engine"
    network_type: int = 2  # Segmentation
    batch_size: int = 1
    process_mode: int = 1  # Primary
    infer_dims: str = "3;1008;1008"
    maintain_aspect_ratio: bool = True
    segmentation_threshold: float = 0.5
    interval: int = 4  # Keyframe interval
    network_mode: int = 1  # FP16
    enable_dla: bool = False
    dla_core: int = 0
    workspace_size: int = 4096


def generate_nvinfer_config(
    output_path: Union[str, Path],
    engine_path: Union[str, Path],
    config: Optional[SAM3DeepStreamConfig] = None,
    nvinfer_config: Optional[NvInferConfig] = None,
) -> Path:
    """
    Generate nvinfer configuration file for DeepStream.

    Args:
        output_path: Path for output config file
        engine_path: Path to TensorRT engine file
        config: SAM3DeepStream configuration
        nvinfer_config: Optional custom nvinfer settings

    Returns:
        Path to generated config file
    """
    if config is None:
        config = get_config()

    if nvinfer_config is None:
        nvinfer_config = NvInferConfig()

    # Apply settings from main config
    nvinfer_config.gpu_id = config.deepstream.gpu_id
    nvinfer_config.interval = config.inference.keyframe_interval - 1
    nvinfer_config.batch_size = config.inference.batch_size
    nvinfer_config.segmentation_threshold = config.inference.segmentation_threshold
    nvinfer_config.model_engine_file = str(engine_path)

    # Set precision mode
    if config.trt.precision == Precision.FP32:
        nvinfer_config.network_mode = 0
    elif config.trt.precision == Precision.FP16:
        nvinfer_config.network_mode = 1
    elif config.trt.precision == Precision.INT8:
        nvinfer_config.network_mode = 2

    # DLA settings
    nvinfer_config.enable_dla = config.trt.use_dla
    nvinfer_config.dla_core = config.trt.dla_core

    # Generate config content
    content = f"""# SAM3 TensorRT nvinfer configuration for DeepStream
# Auto-generated by sam3_deepstream

[property]
gpu-id={nvinfer_config.gpu_id}
net-scale-factor={nvinfer_config.net_scale_factor}

# Model files
model-engine-file={nvinfer_config.model_engine_file}

# Network configuration
network-type={nvinfer_config.network_type}
batch-size={nvinfer_config.batch_size}
process-mode={nvinfer_config.process_mode}

# Input specifications
infer-dims={nvinfer_config.infer_dims}
maintain-aspect-ratio={1 if nvinfer_config.maintain_aspect_ratio else 0}

# Segmentation threshold
segmentation-threshold={nvinfer_config.segmentation_threshold}

# Keyframe interval
interval={nvinfer_config.interval}

# Precision mode
network-mode={nvinfer_config.network_mode}

# DLA configuration
enable-dla={1 if nvinfer_config.enable_dla else 0}
use-dla-core={nvinfer_config.dla_core}

# Memory settings
workspace-size={nvinfer_config.workspace_size}

# Output configuration
output-blob-names=features
"""

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content)

    logger.info(f"Generated nvinfer config: {output_path}")
    return output_path
