"""NvDCF tracker configuration generation."""

import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional, Union

from ..config import get_config, SAM3DeepStreamConfig

logger = logging.getLogger(__name__)


@dataclass
class TrackerConfig:
    """NvDCF tracker configuration settings."""
    # Target management
    max_targets_per_stream: int = 50
    probation_age: int = 3
    max_shadow_tracking_age: int = 30
    max_coasted_tracking_age: int = 60

    # Data association
    association_matcher_type: int = 1  # CASCADED
    matching_score_weight_iou: float = 0.6
    matching_score_weight_visual: float = 0.4
    min_matching_score: float = 0.3
    min_iou_threshold: float = 0.2

    # NvDCF specific
    use_color_names: bool = True
    use_hog: bool = True
    feature_img_size_level: int = 2
    search_region_padding_scale: float = 2.0
    filter_lr: float = 0.15
    high_score_threshold: float = 0.4
    low_score_threshold: float = 0.2


def generate_tracker_config(
    output_path: Union[str, Path],
    config: Optional[SAM3DeepStreamConfig] = None,
    tracker_config: Optional[TrackerConfig] = None,
) -> Path:
    """
    Generate NvDCF tracker configuration file.

    Args:
        output_path: Path for output config file
        config: SAM3DeepStream configuration
        tracker_config: Optional custom tracker settings

    Returns:
        Path to generated config file
    """
    if config is None:
        config = get_config()

    if tracker_config is None:
        tracker_config = TrackerConfig()

    # Apply settings from main config
    tracker_config.max_targets_per_stream = config.inference.max_objects

    content = f"""%YAML:1.0
# NvDCF Tracker Configuration
# Auto-generated by sam3_deepstream

BaseConfig:
  tracker_type: NvDCF
  gpuId: {config.deepstream.gpu_id}
  enable_past_frame: 1

TargetManagement:
  maxTargetsPerStream: {tracker_config.max_targets_per_stream}
  probationAge: {tracker_config.probation_age}
  maxShadowTrackingAge: {tracker_config.max_shadow_tracking_age}
  maxCoastedTrackingAge: {tracker_config.max_coasted_tracking_age}
  earlyTerminationAge: 1

DataAssociator:
  associationMatcherType: {tracker_config.association_matcher_type}
  matchingScoreWeight4Iou: {tracker_config.matching_score_weight_iou}
  matchingScoreWeight4VisualSimilarity: {tracker_config.matching_score_weight_visual}
  minMatchingScore4Overall: {tracker_config.min_matching_score}
  minIouThreshold4Tracker: {tracker_config.min_iou_threshold}
  smoothLocationPredictor: 1
  useKalmanFilter: 1

NvDCF:
  useColorNames: {1 if tracker_config.use_color_names else 0}
  useHog: {1 if tracker_config.use_hog else 0}
  featureImgSizeLevel: {tracker_config.feature_img_size_level}
  searchRegionPaddingScale: {tracker_config.search_region_padding_scale}
  filterLr: {tracker_config.filter_lr}
  filterCfRegLambda: 0.1
  gaussianSigma: 0.6
  numScales: 3
  scaleStep: 1.05
  scaleFilterLr: 0.025
  highScoreThreshold: {tracker_config.high_score_threshold}
  lowScoreThreshold: {tracker_config.low_score_threshold}

StateEstimator:
  processNoiseVarX: 0.1
  processNoiseVarY: 0.1
  processNoiseVarW: 0.04
  processNoiseVarH: 0.04
  measurementNoiseVarX: 0.1
  measurementNoiseVarY: 0.1
  measurementNoiseVarW: 0.1
  measurementNoiseVarH: 0.1
"""

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content)

    logger.info(f"Generated tracker config: {output_path}")
    return output_path
